num1=int(input("введите 1-е число: "))      
num2=int(input("введите 2-е число: "))
num3=int(input("введите 3-е число: "))
print(f"результат суммы:    {num1+num2+num3}")
print(f"результат множения: {num1*num2*num3}")
print("вторая задача")
print("остаток после выплат")
num1=float(input("введите ведите доход за месяц: "))
num2=float(input("введите банковский платёж: "))
num3=float(input("ведите задолжность комунальных услуг: "))
num4=float(num2+num3)
print(f"остаток после выплат: "(num1-num4))
